spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username=postgres
spring.datasource.password=30519

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true