CREATE TABLE categories (
	category_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	category_name VARCHAR(50) NOT NULL UNIQUE,
	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TYPE product_status AS ENUM ('ACTIVE', 'INACTIVE');

CREATE TABLE products (
	product_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	product_name VARCHAR(100) NOT NULL,
	category_id BIGINT NOT NULL,
	price INTEGER NOT NULL CHECK (price >= 0),
	image_url VARCHAR(255),
	description TEXT,
	status product_status NOT NULL DEFAULT 'ACTIVE',
	stock INTEGER NOT NULL CHECK (stock >= 0),
	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT fk_products_categories
		FOREIGN KEY (category_id) REFERENCES categories(category_id)
);